// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wscvfkjtvweztzoxjhyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzY3Zma2p0dndlenR6b3hqaHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NDg4OTMsImV4cCI6MjA4ODAyNDg5M30.msDRcZ5l3CsxgPmkNIoeiR9s2ADMlPQIhjyRDKvey5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});